title: ""
#email: ""
description: ""
baseurl: ""
url: ""
#twitter_username: ""
#github_username:  ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Modify line to update index.html thx
# Page update 2
# and 3
# Last update did not work, let's try again !
# A
# B
