title: ""
#email: ""
description: ""
baseurl: "" 
url: ""
#twitter_username: ""
#github_username:  ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Modify line to update index.html thx
# Page update 2
